name: Balancing Feedback
about: Create a feedback to balance an item/block
title: "Title"
labels: [invalid]
body:
  - type: textarea
    id: description
    attributes:
      label: "What is the overpowered item/block?"
    validations:
      required: true
  - type: textarea
    id: description2
    attributes:
      label: "Why is an item/block overpowered?"
    validations:
      required: true
  - type: textarea
    id: description3
    attributes:
      label: "How to balance the item/block?"
    validations:
      required: true
  - type: textarea
    id: optionaldescription
    attributes:
      label: "Additional context"
    validations:
      required: false
