name: Bug Report
about: Create a report to improve the mod
title: ''
labels: ''
assignees: ''
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug."
    validations:
      required: true
  - type: textarea
    id: description2
    attributes:
      label: "How to Reproduce the bug?"
    validations:
      required: true
  - type: textarea
    id: description3
    attributes:
      label: "Expected Behavior."
    validations:
      required: true
  - type: textarea
    id: optionaldescription
    attributes:
      label: "Additional context."
    validations:
      required: false
